export { default as HomePage } from './HomePage'
export { default as WelcomePage } from './WelcomePage'
export { default as MapPage } from './MapPage'
export { default as MathPage } from './MathPage'
export { default as WordScramblePage } from './WordScramblePage'
export { default as ResultPage } from './ResultPage'
export { default as GuessItSpellIt } from './GuessItSpellIt'